version: '3.1'

services:
  starlite_wp:
    image: wordpress:latest
    container_name: starlite_wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_NAME=starlite
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=starlite_db
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=7P3tfpuVCi6X4e1V
    depends_on:
      - starlite_db
      - starlite_phpmyadmin
    restart: always
    ports:
      - 8037:80

  starlite_db:
    container_name: starlite_db
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7P3tfpuVCi6X4e1V
      MYSQL_DATABASE: starlite
      MYSQL_USER: user
      MYSQL_PASSWORD: 7P3tfpuVCi6X4e1V
    volumes:
      - starlite_db_data:/var/lib/mysql

  starlite_phpmyadmin:
    container_name: starlite_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8038:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=starlite_db
      - PMA_USER=root
      - PMA_PASSWORD=7P3tfpuVCi6X4e1V

volumes:
  starlite_db_data:
